### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by lukasbystricky** [erinendrei/g-e-moore_principia-ethica#2]
- [x] content.opf, line 43: "good" is double quoted inside a larger quote. Replace with single quotes
- [x] content.opf, line 45: These theorists “describe the Supreme Good in ‘metaphysical’ terms,’ ” “in terms of something which (they hold) does exist, but does not exist in Nature—in terms of a supersensible reality.” Looks like something is wrong with the quotes here. If you're quoting two non-connected phrases of Moore's you can use "[...]".
- [x] content.opf, line 55: predicability -> predictability

**Comment by erinendrei** [comment]
line 43: this is fixed now; thanks.

line 45: the extraneous quotation mark has been removed and I rephrased a little so that the quotations aren't immediately adjacent.

line 55: I didn't mean "predictability", but "predicability" as in the quality or state of being [predicable](https://www.merriam-webster.com/dictionary/predicable). I used the word partly because Moore is often talking about predicates, especially "the predicate 'good'". But since "predicability" is not a common word and on second thoughts concepts are probably better said to be applied than predicated, I've changed it to "applicability".
