### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by lukasbystricky** [erinendrei/g-e-moore_principia-ethica#3]
Sorry, a couple last minute things. In the prefaces, the datelines, signatures etc should be tagged and put into a footer. You'll also need some CSS for that. See [here](https://standardebooks.org/manual/1.7.3/single-page#7.7) for how to structure that. Ignore the letter blockquote, just follow the footer structure and appropriate semantics.

**Comment by erinendrei** [comment]
Thanks. Since my last book had a footer in the preface I should have remembered that. I added the footer tags and signature semantic. But are dateline and datetime necessary for "August, 1903" and "Cambridge, 1922"? The footer example in [8.10.4](https://standardebooks.org/manual/1.7.3/single-page#8.10.4) of the manual suggests they're not. There seem to be quite a lot of other examples of books with footers containing locations and months that don't have dateline/datetime: [Vanity Fair](https://github.com/standardebooks/william-makepeace-thackeray_vanity-fair/blob/8a55e3407dd5c2ea88dc043863a632c9e081ed60/src/epub/text/prologue.xhtml#L16), [Jeeves Stories](https://github.com/standardebooks/p-g-wodehouse_jeeves-stories/blob/e172d31c8d0fae76699927f06ca0a9fd90e50815/src/epub/text/editors-preface.xhtml#L15), [David Copperfield](https://github.com/standardebooks/charles-dickens_david-copperfield/blob/f0722fe7db3d6eb7adbc1768d656d066b7dddbb7/src/epub/text/preface-1850.xhtml#L15) (which actually has z3998:signature for the location and month, which seems odd), [The Age of Reason](https://github.com/standardebooks/thomas-paine_the-age-of-reason/blob/953c2fb7ddad1a2e12609f1113eabb49f2ad0e06/src/epub/text/part-2-preface.xhtml#L27), [Tess of the D'Urbervilles](https://github.com/standardebooks/thomas-hardy_tess-of-the-durbervilles/blob/175b7cb015db630ee30406fa167898125f93ccb7/src/epub/text/preface.xhtml#L13), [A Tangled Tale](https://github.com/standardebooks/lewis-carroll_a-tangled-tale/blob/1f37d21159f11838cda764b3b73f0544140936e6/src/epub/text/preface.xhtml#L12).

**Comment by lukasbystricky** [comment]
Yeah it seems to be one of those things that we're not especially picky on. There are several cases where a datetime is included in the preface footer (see [here](https://github.com/search?q=owner%3Astandardebooks+path%3Asrc%2Fepub%2Ftext%2Fpreface.xhtml+datetime&type=code)). Strictly speaking I think it's the correct semantic to add.

**Comment by erinendrei** [comment]
OK, that's good to know, thanks. I added it.
